"""asset scan credentials

Revision ID: a7a1dba56c1b
Revises: 3683d07c2f17
Create Date: 2026-08-05 17:12:47.979042
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7a1dba56c1b'
down_revision: Union[str, None] = '3683d07c2f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('auth_type', sa.Enum('COOKIE', 'BEARER', 'HEADER', name='authtype'), nullable=False),
    sa.Column('header_name', sa.String(length=64), nullable=True),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_credentials_asset_id'), 'asset_credentials', ['asset_id'], unique=True)
    op.create_index(op.f('ix_asset_credentials_org_id'), 'asset_credentials', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_credentials_org_id'), table_name='asset_credentials')
    op.drop_index(op.f('ix_asset_credentials_asset_id'), table_name='asset_credentials')
    op.drop_table('asset_credentials')
    # ### end Alembic commands ###
