"""
Siege Tower — extended playbook.

Breadth additions layered on top of the core external-to-domain chain in
`playbook.py`: more initial-access options, execution/persistence, additional
privilege-escalation and credential-access routes, richer collection and
exfiltration, more impact variants, and full cloud and email-compromise chains.

Every play is wired into the same capability graph, so the engine can compose
these with the core plays into many distinct, minimal plans. Kept in its own
module so each domain stays reviewable; `playbook.py` concatenates it into
DEFAULT_PLAYBOOK.

Commands are illustrative starting points for authorized engagements only.
"""
from __future__ import annotations

from .capabilities import (
    CAP_AD_RECON, CAP_C2, CAP_CLOUD_ACCOUNT, CAP_CLOUD_ADMIN, CAP_CLOUD_RECON,
    CAP_CODE_EXEC_HOST, CAP_DATA_EXFILTRATED, CAP_DOMAIN_ADMIN, CAP_DOMAIN_USER,
    CAP_EMAIL_ACCESS, CAP_EXTERNAL_RECON, CAP_HARVESTED_CREDS,
    CAP_IMPACT_DEPLOYED, CAP_INTERNAL_NETWORK, CAP_LOCAL_ADMIN, CAP_PERSISTENCE,
    CAP_PHYSICAL_ONSITE, CAP_SENSITIVE_DATA_ACCESS, CAP_WEB_FOOTHOLD,
)
from .schema import Platform, Play, PlayStep, Tactic

WIN = Platform.WINDOWS
LNX = Platform.LINUX
MAC = Platform.MACOS
WEB = Platform.WEB
NET = Platform.NETWORK
AD = Platform.ACTIVE_DIRECTORY
AZ = Platform.AZURE_AD
CLD = Platform.CLOUD


def _p(command: str, description: str, expected: str) -> PlayStep:
    return PlayStep(command=command, description=description, expected_result=expected)


EXTENDED_PLAYS: list[Play] = [
    # ── More initial access ──────────────────────────────────────
    Play(
        technique_id="T1078",
        name="Valid Accounts on an exposed service",
        tactic=Tactic.INITIAL_ACCESS,
        summary="Reuse recovered credentials directly against an exposed RDP/OWA/portal.",
        requires=frozenset({CAP_DOMAIN_USER}),
        provides=frozenset({CAP_INTERNAL_NETWORK, CAP_CODE_EXEC_HOST}),
        platforms=frozenset({WIN, NET, WEB}),
        noise=2, difficulty=2, reliability=4, est_minutes=30,
        objective="Convert known credentials into an internal foothold without exploiting anything.",
        prerequisite_note="Valid domain credentials and a directly exposed service.",
        steps=(
            _p("nxc rdp $HOST -u $USER -p $PASS", "Confirm the creds work on the exposed service.", "Successful authentication banner."),
            _p("xfreerdp /u:$USER /p:$PASS /v:$HOST", "Log in interactively.", "A desktop/session on an internal host."),
        ),
        success_indicator="Authenticated interactive access to an internal host.",
        fallback_technique_ids=("T1133", "T1566"),
        detection="Logins from atypical sources; impossible-travel sign-ins.",
        references=("https://attack.mitre.org/techniques/T1078/",),
    ),
    Play(
        technique_id="T1195",
        name="Supply Chain Compromise",
        tactic=Tactic.INITIAL_ACCESS,
        summary="Reach execution through a trusted software/update dependency.",
        requires=frozenset({CAP_EXTERNAL_RECON}),
        provides=frozenset({CAP_CODE_EXEC_HOST, CAP_C2}),
        platforms=frozenset({WIN, LNX, WEB}),
        noise=1, difficulty=5, reliability=2, est_minutes=480,
        objective="Gain execution via a component the target already trusts.",
        prerequisite_note="A modifiable dependency, package, or update channel in scope.",
        steps=(
            _p("# identify a build/dependency the target ingests", "Map the software supply chain in scope.", "A tamperable component is identified."),
            _p("# stage a benign, tracked marker payload with sign-off", "Introduce a controlled artifact that beacons.", "Execution when the component is consumed."),
        ),
        success_indicator="A beacon returns from a host via the trusted component.",
        fallback_technique_ids=("T1190", "T1566"),
        detection="Unexpected outbound from build agents; changed artifact hashes.",
        attributed_actors=frozenset({"APT29"}),
        references=("https://attack.mitre.org/techniques/T1195/",),
    ),
    Play(
        technique_id="T1199",
        name="Trusted Relationship",
        tactic=Tactic.INITIAL_ACCESS,
        summary="Enter through a third party/managed-service connection into the network.",
        requires=frozenset({CAP_EXTERNAL_RECON}),
        provides=frozenset({CAP_INTERNAL_NETWORK, CAP_DOMAIN_USER}),
        platforms=frozenset({NET, WIN}),
        noise=2, difficulty=3, reliability=3, est_minutes=120,
        objective="Abuse a trusted external connection to land inside the perimeter.",
        prerequisite_note="A partner/MSP/VPN trust reachable and in scope.",
        steps=(
            _p("# enumerate partner/MSP ingress in scope", "Find the trusted connection.", "A trusted ingress path is identified."),
            _p("# authenticate through the trusted channel", "Use the relationship to reach the LAN.", "Internal access via the trusted path."),
        ),
        success_indicator="Internal access obtained through a trusted external party.",
        fallback_technique_ids=("T1133",),
        detection="Partner accounts acting outside their normal pattern.",
        references=("https://attack.mitre.org/techniques/T1199/",),
    ),
    Play(
        technique_id="T1189",
        name="Drive-by Compromise",
        tactic=Tactic.INITIAL_ACCESS,
        summary="Compromise a user via a malicious or watering-hole web page.",
        requires=frozenset({CAP_EXTERNAL_RECON}),
        provides=frozenset({CAP_CODE_EXEC_HOST, CAP_C2}),
        platforms=frozenset({WIN, WEB}),
        noise=3, difficulty=3, reliability=2, est_minutes=180,
        is_social_engineering=True,
        objective="Land execution when a targeted user browses attacker-controlled content.",
        prerequisite_note="A plausible lure site and a target population.",
        steps=(
            _p("# host the lure / poison a frequented site (with authorization)", "Stage the browser delivery.", "Payload served to visiting users."),
        ),
        success_indicator="A beacon returns from a user who browsed the page.",
        fallback_technique_ids=("T1566",),
        detection="Proxy alerts on newly-registered domains; browser child processes.",
        references=("https://attack.mitre.org/techniques/T1189/",),
    ),
    Play(
        technique_id="T1200",
        name="Hardware Additions (on-site drop)",
        tactic=Tactic.INITIAL_ACCESS,
        summary="Plant a rogue device on the internal network during a physical visit.",
        requires=frozenset({CAP_PHYSICAL_ONSITE}),
        provides=frozenset({CAP_INTERNAL_NETWORK, CAP_CODE_EXEC_HOST}),
        platforms=frozenset({NET}),
        noise=3, difficulty=3, reliability=3, est_minutes=60,
        objective="Establish an internal beachhead via physical access.",
        prerequisite_note="Authorized physical presence and an open port/jack.",
        steps=(
            _p("# connect an implant (e.g. drop box) to a live jack", "Bridge an attacker device onto the LAN.", "The implant obtains a lease and calls home."),
        ),
        success_indicator="A callback from an implant inside the network.",
        fallback_technique_ids=("T1091",),
        detection="NAC/802.1x alerts on an unknown device.",
        references=("https://attack.mitre.org/techniques/T1200/",),
    ),

    # ── Execution / persistence ──────────────────────────────────
    Play(
        technique_id="T1059",
        name="Command and Scripting Interpreter (interactive C2)",
        tactic=Tactic.EXECUTION,
        summary="Upgrade raw execution into a stable, interactive C2 channel.",
        requires=frozenset({CAP_CODE_EXEC_HOST}),
        provides=frozenset({CAP_C2}),
        platforms=frozenset({WIN, LNX, MAC}),
        noise=3, difficulty=1, reliability=4, est_minutes=20,
        objective="Establish reliable, interactive control over the foothold.",
        prerequisite_note="Any code-execution primitive on a host.",
        steps=(
            _p("powershell -enc <staged-beacon>  # or bash reverse shell", "Launch a beacon/agent for interactive control.", "A stable session/beacon checks in."),
        ),
        success_indicator="An interactive C2 session is stable across commands.",
        fallback_technique_ids=("T1505.003",),
        detection="Encoded interpreters spawning; beaconing network patterns.",
        references=("https://attack.mitre.org/techniques/T1059/",),
    ),
    Play(
        technique_id="T1505.003",
        name="Web Shell",
        tactic=Tactic.PERSISTENCE,
        summary="Drop a web shell on a compromised web tier for durable C2.",
        requires=frozenset({CAP_WEB_FOOTHOLD}),
        provides=frozenset({CAP_CODE_EXEC_HOST, CAP_C2, CAP_PERSISTENCE}),
        platforms=frozenset({WEB, WIN, LNX}),
        noise=3, difficulty=2, reliability=4, est_minutes=30,
        is_persistence=True,
        objective="Keep reliable execution on the web server independent of the exploit.",
        prerequisite_note="Write access to a web-served directory.",
        steps=(
            _p("# upload a minimal authenticated web shell to the web root", "Place a durable execution endpoint.", "Commands run via an HTTP request."),
        ),
        success_indicator="Commands execute through the web shell over HTTP(S).",
        fallback_technique_ids=("T1059",),
        detection="New files in web roots; anomalous requests to odd endpoints.",
        references=("https://attack.mitre.org/techniques/T1505/003/",),
    ),
    Play(
        technique_id="T1543",
        name="Create or Modify System Process (service)",
        tactic=Tactic.PRIVILEGE_ESCALATION,
        summary="Abuse service creation/modification for SYSTEM and persistence.",
        requires=frozenset({CAP_CODE_EXEC_HOST}),
        provides=frozenset({CAP_LOCAL_ADMIN, CAP_PERSISTENCE}),
        platforms=frozenset({WIN, LNX}),
        noise=3, difficulty=3, reliability=3, est_minutes=45,
        is_persistence=True,
        objective="Escalate to SYSTEM/root while establishing durable re-entry.",
        prerequisite_note="A weak service ACL, unquoted path, or writable unit file.",
        steps=(
            _p("# reconfigure a writable service binPath to a payload; restart it", "Abuse the service to run as SYSTEM/root.", "A privileged process runs your payload."),
        ),
        success_indicator="A payload runs as SYSTEM/root and survives reboot.",
        fallback_technique_ids=("T1068", "T1548"),
        detection="Service binary-path changes; new services (Sysmon 13/7045).",
        references=("https://attack.mitre.org/techniques/T1543/",),
    ),
    Play(
        technique_id="T1053",
        name="Scheduled Task/Job",
        tactic=Tactic.PERSISTENCE,
        summary="Register a scheduled task/cron job for durable re-entry.",
        requires=frozenset({CAP_CODE_EXEC_HOST}),
        provides=frozenset({CAP_PERSISTENCE}),
        platforms=frozenset({WIN, LNX}),
        noise=2, difficulty=1, reliability=4, est_minutes=20,
        is_persistence=True,
        objective="Guarantee the team can regain access on a schedule.",
        prerequisite_note="Code execution on the host.",
        steps=(
            _p("schtasks /create /sc onlogon /tn Updater /tr <payload>", "Create a triggered task.", "The payload runs on the chosen trigger."),
        ),
        success_indicator="Access is regained automatically after loss.",
        fallback_technique_ids=("T1543",),
        detection="New scheduled tasks / cron entries.",
        references=("https://attack.mitre.org/techniques/T1053/",),
    ),

    # ── More local escalation ────────────────────────────────────
    Play(
        technique_id="T1548",
        name="Abuse Elevation Control Mechanism (UAC / sudo)",
        tactic=Tactic.PRIVILEGE_ESCALATION,
        summary="Bypass UAC or abuse sudo/setuid to reach admin/root.",
        requires=frozenset({CAP_CODE_EXEC_HOST}),
        provides=frozenset({CAP_LOCAL_ADMIN}),
        platforms=frozenset({WIN, LNX, MAC}),
        noise=2, difficulty=2, reliability=3, est_minutes=30,
        objective="Elevate the foothold to local administrator/root.",
        prerequisite_note="A UAC-bypass primitive or a permissive sudo/setuid config.",
        steps=(
            _p("# UAC bypass (fodhelper) or abuse a sudo rule / SUID binary", "Elevate using the confirmed mechanism.", "A high-integrity/root shell."),
        ),
        success_indicator="A shell running as admin/root.",
        fallback_technique_ids=("T1068", "T1543"),
        detection="Known UAC-bypass registry/process patterns; sudo anomalies.",
        references=("https://attack.mitre.org/techniques/T1548/",),
    ),

    # ── More credential access ───────────────────────────────────
    Play(
        technique_id="T1552",
        name="Unsecured Credentials (files, GPP, registry)",
        tactic=Tactic.CREDENTIAL_ACCESS,
        summary="Harvest passwords left in scripts, shares, GPP, or the registry.",
        requires=frozenset({CAP_CODE_EXEC_HOST}),
        provides=frozenset({CAP_HARVESTED_CREDS, CAP_DOMAIN_USER}),
        platforms=frozenset({WIN, LNX}),
        noise=1, difficulty=2, reliability=3, est_minutes=45,
        objective="Recover domain credentials without touching LSASS.",
        prerequisite_note="Read access to shares/config likely to hold secrets.",
        steps=(
            _p("# search SYSVOL for GPP cpassword; grep configs for secrets", "Look where credentials are commonly left.", "Recoverable credential material."),
            _p("gpp-decrypt <cpassword>", "Decrypt any GPP passwords found.", "A cleartext domain password."),
        ),
        success_indicator="Valid domain credentials recovered from stored data.",
        fallback_technique_ids=("T1555", "T1003"),
        detection="Bulk SYSVOL reads; access to sensitive config paths.",
        references=("https://attack.mitre.org/techniques/T1552/",),
    ),
    Play(
        technique_id="T1555",
        name="Credentials from Password Stores",
        tactic=Tactic.CREDENTIAL_ACCESS,
        summary="Loot browser, KeePass, and OS credential stores on the host.",
        requires=frozenset({CAP_CODE_EXEC_HOST}),
        provides=frozenset({CAP_HARVESTED_CREDS}),
        platforms=frozenset({WIN, LNX, MAC}),
        noise=2, difficulty=2, reliability=3, est_minutes=30,
        objective="Recover reusable secrets cached by applications.",
        prerequisite_note="User-context execution on the host.",
        steps=(
            _p("# dump browser logins / Windows Credential Manager / keychain", "Extract stored application credentials.", "Cleartext or reusable secrets."),
        ),
        success_indicator="Reusable credentials or tokens recovered.",
        fallback_technique_ids=("T1552",),
        detection="Access to browser credential DBs; credential-store reads.",
        references=("https://attack.mitre.org/techniques/T1555/",),
    ),
    Play(
        technique_id="T1187",
        name="Forced Authentication / LLMNR-NBNS poisoning",
        tactic=Tactic.CREDENTIAL_ACCESS,
        summary="Poison name resolution to capture and crack net-NTLM hashes.",
        requires=frozenset({CAP_INTERNAL_NETWORK}),
        provides=frozenset({CAP_HARVESTED_CREDS, CAP_DOMAIN_USER}),
        platforms=frozenset({WIN, NET, AD}),
        noise=3, difficulty=2, reliability=3, est_minutes=120,
        objective="Obtain domain credentials from the wire without any foothold creds.",
        prerequisite_note="LAN access where LLMNR/NBT-NS/mDNS is enabled.",
        steps=(
            _p("responder -I eth0 -wtv", "Answer broadcast name lookups to capture auth.", "Net-NTLMv2 hashes from responding hosts."),
            _p("hashcat -m 5600 captured.txt rockyou.txt", "Crack the captured hashes offline.", "A cleartext domain password."),
        ),
        success_indicator="A crackable/relayable hash yields valid credentials.",
        fallback_technique_ids=("T1557",),
        detection="Rogue LLMNR/NBT-NS responders; poisoning signatures.",
        references=("https://attack.mitre.org/techniques/T1187/",),
    ),
    Play(
        technique_id="T1558.004",
        name="AS-REP Roasting",
        tactic=Tactic.CREDENTIAL_ACCESS,
        summary="Crack accounts that don't require Kerberos pre-authentication.",
        requires=frozenset({CAP_DOMAIN_USER, CAP_AD_RECON}),
        provides=frozenset({CAP_HARVESTED_CREDS}),
        platforms=frozenset({AD, WIN}),
        noise=2, difficulty=3, reliability=2, est_minutes=120,
        is_credential_bruteforce=True,
        objective="Recover additional account passwords to widen privileged reach.",
        prerequisite_note="Accounts with 'do not require pre-auth' set.",
        steps=(
            _p("GetNPUsers.py -request $DOMAIN/ -usersfile users.txt -no-pass", "Request AS-REP for pre-auth-disabled accounts.", "AS-REP hashes to crack."),
            _p("hashcat -m 18200 asrep.txt rockyou.txt", "Crack offline.", "Cleartext passwords for those accounts."),
        ),
        success_indicator="Cracked credentials expand access.",
        fallback_technique_ids=("T1558.003",),
        detection="AS-REP requests for many users with pre-auth disabled.",
        references=("https://attack.mitre.org/techniques/T1558/004/",),
    ),

    # ── More discovery ───────────────────────────────────────────
    Play(
        technique_id="T1482",
        name="Domain Trust Discovery",
        tactic=Tactic.DISCOVERY,
        summary="Map domain/forest trusts to find the fastest privileged path.",
        requires=frozenset({CAP_DOMAIN_USER, CAP_INTERNAL_NETWORK}),
        provides=frozenset({CAP_AD_RECON}),
        platforms=frozenset({AD, WIN}),
        noise=2, difficulty=2, reliability=4, est_minutes=30,
        objective="Understand trusts and ACLs to choose an escalation route.",
        prerequisite_note="Any domain identity with LAN access.",
        steps=(
            _p("nltest /domain_trusts  # and enumerate ACLs", "Enumerate trusts and delegation.", "Trust map and abusable relationships."),
        ),
        success_indicator="A concrete escalation path is selected.",
        fallback_technique_ids=("T1087",),
        detection="Trust/ACL enumeration bursts from one host.",
        references=("https://attack.mitre.org/techniques/T1482/",),
    ),

    # ── More domain escalation ───────────────────────────────────
    Play(
        technique_id="T1484.001",
        name="Group Policy (GPO) abuse",
        tactic=Tactic.PRIVILEGE_ESCALATION,
        summary="Abuse write access to a GPO to push code to privileged hosts.",
        requires=frozenset({CAP_DOMAIN_USER, CAP_AD_RECON}),
        provides=frozenset({CAP_DOMAIN_ADMIN}),
        platforms=frozenset({AD, WIN}),
        noise=3, difficulty=3, reliability=3, est_minutes=90,
        objective="Escalate to Tier-0 by abusing a writable GPO linked to key OUs.",
        prerequisite_note="Write rights on a GPO from the AD ACL review.",
        steps=(
            _p("# use SharpGPOAbuse to add an immediate scheduled task via the GPO", "Push a task to targeted computers/users.", "Code runs on a Tier-0 host."),
        ),
        success_indicator="Execution lands on a domain controller / Tier-0 asset.",
        fallback_technique_ids=("T1649", "T1558.003"),
        detection="Unexpected GPO edits; new immediate scheduled tasks.",
        references=("https://attack.mitre.org/techniques/T1484/001/",),
    ),
    Play(
        technique_id="T1021.002",
        name="Pass-the-Hash to a Domain Controller",
        tactic=Tactic.LATERAL_MOVEMENT,
        summary="Reuse a looted privileged hash to authenticate to a DC.",
        requires=frozenset({CAP_HARVESTED_CREDS, CAP_INTERNAL_NETWORK}),
        provides=frozenset({CAP_DOMAIN_ADMIN}),
        platforms=frozenset({WIN, AD, NET}),
        noise=3, difficulty=2, reliability=3, est_minutes=30,
        objective="Turn a privileged hash into domain-wide control.",
        prerequisite_note="A looted admin/DA-equivalent NTLM hash.",
        steps=(
            _p("nxc smb $DC -u Administrator -H $NTLM -x whoami", "Authenticate to the DC with the hash.", "Command output as a privileged account."),
        ),
        success_indicator="Privileged command execution on a domain controller.",
        fallback_technique_ids=("T1003.006",),
        detection="Pass-the-hash patterns; admin logons from unusual hosts.",
        references=("https://attack.mitre.org/techniques/T1021/002/",),
    ),

    # ── More collection ──────────────────────────────────────────
    Play(
        technique_id="T1039",
        name="Data from Network Shared Drive",
        tactic=Tactic.COLLECTION,
        summary="Collect objective data from reachable SMB/NFS shares.",
        requires=frozenset({CAP_DOMAIN_USER}),
        provides=frozenset({CAP_SENSITIVE_DATA_ACCESS}),
        platforms=frozenset({WIN, AD}),
        noise=2, difficulty=1, reliability=4, est_minutes=45,
        objective="Locate and stage in-scope data on file shares.",
        prerequisite_note="A domain identity with share access.",
        steps=(
            _p("nxc smb $RANGE -u $USER -p $PASS -M spider_plus", "Enumerate and index reachable shares.", "A map of sensitive files across shares."),
        ),
        success_indicator="Objective data located and staged.",
        fallback_technique_ids=("T1213", "T1005"),
        detection="Broad share access from a single account.",
        references=("https://attack.mitre.org/techniques/T1039/",),
    ),
    Play(
        technique_id="T1114",
        name="Email Collection (on-prem Exchange)",
        tactic=Tactic.COLLECTION,
        summary="Access target mailboxes on an on-prem mail system.",
        requires=frozenset({CAP_DOMAIN_USER}),
        provides=frozenset({CAP_EMAIL_ACCESS, CAP_SENSITIVE_DATA_ACCESS}),
        platforms=frozenset({WIN, AD}),
        noise=2, difficulty=2, reliability=3, est_minutes=60,
        objective="Read/stage mailbox contents relevant to the objective.",
        prerequisite_note="A domain identity (or app impersonation) with mailbox rights.",
        steps=(
            _p("# use EWS/MAPI with delegated or impersonation rights", "Access the target mailbox(es).", "Readable mailbox content."),
        ),
        success_indicator="Target mailbox content is accessible.",
        fallback_technique_ids=("T1114.002",),
        detection="Mailbox impersonation; unusual EWS access.",
        references=("https://attack.mitre.org/techniques/T1114/",),
    ),

    # ── More exfiltration ────────────────────────────────────────
    Play(
        technique_id="T1041",
        name="Exfiltration Over C2 Channel",
        tactic=Tactic.EXFILTRATION,
        summary="Send staged data back through the existing C2 channel.",
        requires=frozenset({CAP_SENSITIVE_DATA_ACCESS, CAP_C2}),
        provides=frozenset({CAP_DATA_EXFILTRATED}),
        platforms=frozenset({WIN, LNX, MAC, WEB}),
        noise=2, difficulty=2, reliability=4, est_minutes=40,
        objective="Prove exfiltration using the channel you already control.",
        prerequisite_note="Staged data and an established C2 channel.",
        steps=(
            _p("# tunnel the archive back over the beacon's C2", "Move data inside existing C2 traffic.", "Archive received at the team sink."),
        ),
        success_indicator="Data arrives intact via C2.",
        fallback_technique_ids=("T1567", "T1048"),
        detection="Beacon volume anomalies; large C2 transfers.",
        references=("https://attack.mitre.org/techniques/T1041/",),
    ),
    Play(
        technique_id="T1048",
        name="Exfiltration Over Alternative Protocol (DNS/ICMP)",
        tactic=Tactic.EXFILTRATION,
        summary="Tunnel data out over DNS or another permitted protocol.",
        requires=frozenset({CAP_SENSITIVE_DATA_ACCESS, CAP_CODE_EXEC_HOST}),
        provides=frozenset({CAP_DATA_EXFILTRATED}),
        platforms=frozenset({WIN, LNX, NET}),
        noise=3, difficulty=3, reliability=3, est_minutes=60,
        objective="Demonstrate exfiltration over a channel egress filtering misses.",
        prerequisite_note="Outbound DNS/ICMP the team is permitted to use.",
        steps=(
            _p("# chunk + encode the archive; exfil via DNS TXT queries", "Tunnel the data over DNS.", "Reassembled archive at the team resolver."),
        ),
        success_indicator="Data reassembles at the team-controlled endpoint.",
        fallback_technique_ids=("T1567",),
        detection="High-volume/entropy DNS to one domain (DLP/NDR).",
        references=("https://attack.mitre.org/techniques/T1048/",),
    ),

    # ── More impact (simulated) ──────────────────────────────────
    Play(
        technique_id="T1490",
        name="Inhibit System Recovery (SIMULATED)",
        tactic=Tactic.IMPACT,
        summary="Demonstrate recovery-inhibition reach with reversible, tracked actions.",
        requires=frozenset({CAP_DOMAIN_ADMIN}),
        provides=frozenset({CAP_IMPACT_DEPLOYED}),
        platforms=frozenset({WIN}),
        noise=5, difficulty=2, reliability=4, est_minutes=45,
        destructive=True, requires_evidence_removal=True,
        objective="Prove the blast radius for recovery-inhibition without real harm.",
        prerequisite_note="Explicit written sign-off for a simulated impact action.",
        steps=(
            _p("# demonstrate the capability on a designated canary host, then revert", "Show reach on an agreed target only.", "Documented reach; fully reverted."),
        ),
        success_indicator="Reach demonstrated on the agreed scope and reverted.",
        fallback_technique_ids=("T1486",),
        detection="Shadow-copy/backup tampering; EDR ransomware canaries.",
        references=("https://attack.mitre.org/techniques/T1490/",),
    ),
    Play(
        technique_id="T1485",
        name="Data Destruction (SIMULATED)",
        tactic=Tactic.IMPACT,
        summary="Demonstrate destructive reach using a benign, reversible marker.",
        requires=frozenset({CAP_DOMAIN_ADMIN}),
        provides=frozenset({CAP_IMPACT_DEPLOYED}),
        platforms=frozenset({WIN, LNX}),
        noise=5, difficulty=2, reliability=3, est_minutes=45,
        destructive=True, requires_evidence_removal=True,
        objective="Evidence the ability to destroy data without destroying any.",
        prerequisite_note="Explicit written sign-off; canary targets only.",
        steps=(
            _p("# write a tracked benign marker to a designated canary set, then remove", "Simulate destruction on agreed targets.", "Reach documented; markers removed."),
        ),
        success_indicator="Capability evidenced on the agreed scope and reverted.",
        fallback_technique_ids=("T1486", "T1490"),
        detection="Mass deletes/overwrites; EDR impact heuristics.",
        references=("https://attack.mitre.org/techniques/T1485/",),
    ),

    # ── Cloud chain ──────────────────────────────────────────────
    Play(
        technique_id="T1078.004",
        name="Valid Cloud Accounts (password spray / AiTM)",
        tactic=Tactic.INITIAL_ACCESS,
        summary="Obtain valid cloud (Entra ID/M365) credentials from the internet.",
        requires=frozenset({CAP_EXTERNAL_RECON}),
        provides=frozenset({CAP_CLOUD_ACCOUNT}),
        platforms=frozenset({AZ, CLD}),
        noise=4, difficulty=2, reliability=2, est_minutes=120,
        is_credential_bruteforce=True,
        objective="Get a first authenticated identity in the cloud tenant.",
        prerequisite_note="A discovered tenant and a user list.",
        steps=(
            _p("# spray M365/Entra sign-in, or run an AiTM proxy to capture tokens", "Recover valid cloud credentials or session tokens.", "A working cloud sign-in / token."),
        ),
        success_indicator="A cloud identity authenticates to the tenant.",
        fallback_technique_ids=("T1566.002",),
        detection="Entra sign-in risk; impossible travel; token anomalies.",
        attributed_actors=frozenset({"APT29"}),
        references=("https://attack.mitre.org/techniques/T1078/004/",),
    ),
    Play(
        technique_id="T1566.002",
        name="OAuth consent / spearphishing link",
        tactic=Tactic.INITIAL_ACCESS,
        summary="Trick a user into granting an app or leaking a cloud token.",
        requires=frozenset({CAP_EXTERNAL_RECON}),
        provides=frozenset({CAP_CLOUD_ACCOUNT}),
        platforms=frozenset({AZ, CLD}),
        noise=3, difficulty=3, reliability=3, est_minutes=120,
        is_phishing=True, is_social_engineering=True,
        objective="Obtain cloud access via consented app permissions or captured tokens.",
        prerequisite_note="Target users and a sending channel.",
        steps=(
            _p("# deliver an OAuth consent lure for a malicious app registration", "Get a user to grant delegated permissions.", "A refresh token / app access to the tenant."),
        ),
        success_indicator="Delegated cloud access is obtained.",
        fallback_technique_ids=("T1078.004",),
        detection="Illicit consent grants; risky OAuth apps.",
        attributed_actors=frozenset({"APT29"}),
        references=("https://attack.mitre.org/techniques/T1566/002/",),
    ),
    Play(
        technique_id="T1552.005",
        name="Cloud Instance Metadata API (SSRF)",
        tactic=Tactic.CREDENTIAL_ACCESS,
        summary="Pivot an on-prem web foothold into cloud credentials via SSRF.",
        requires=frozenset({CAP_WEB_FOOTHOLD}),
        provides=frozenset({CAP_CLOUD_ACCOUNT}),
        platforms=frozenset({CLD, WEB}),
        noise=2, difficulty=3, reliability=3, est_minutes=45,
        objective="Steal an instance role's credentials from the metadata service.",
        prerequisite_note="An SSRF-able request path from a cloud-hosted web app.",
        steps=(
            _p("curl http://169.254.169.254/latest/meta-data/iam/security-credentials/", "Reach the metadata endpoint via SSRF.", "Temporary cloud role credentials."),
        ),
        success_indicator="Cloud role credentials are recovered and usable.",
        fallback_technique_ids=("T1078.004",),
        detection="Metadata endpoint access from a web process; SSRF WAF hits.",
        references=("https://attack.mitre.org/techniques/T1552/005/",),
    ),
    Play(
        technique_id="T1526",
        name="Cloud Service Discovery",
        tactic=Tactic.DISCOVERY,
        summary="Enumerate the tenant: roles, apps, storage, and escalation paths.",
        requires=frozenset({CAP_CLOUD_ACCOUNT}),
        provides=frozenset({CAP_CLOUD_RECON}),
        platforms=frozenset({CLD, AZ}),
        noise=2, difficulty=2, reliability=5, est_minutes=45,
        objective="Find the shortest path to a privileged cloud role.",
        prerequisite_note="Any authenticated cloud identity.",
        steps=(
            _p("# run ROADrecon / AzureHound / ScoutSuite against the tenant", "Map identities, roles, and misconfigurations.", "A concrete cloud escalation path."),
        ),
        success_indicator="A viable path to a privileged role is identified.",
        fallback_technique_ids=("T1087",),
        detection="Bulk Graph/ARM enumeration from one principal.",
        references=("https://attack.mitre.org/techniques/T1526/",),
    ),
    Play(
        technique_id="T1098",
        name="Account Manipulation (cloud role/credential abuse)",
        tactic=Tactic.PRIVILEGE_ESCALATION,
        summary="Escalate to tenant admin via role assignment or app credentials.",
        requires=frozenset({CAP_CLOUD_ACCOUNT, CAP_CLOUD_RECON}),
        provides=frozenset({CAP_CLOUD_ADMIN}),
        platforms=frozenset({AZ, CLD}),
        noise=3, difficulty=3, reliability=3, est_minutes=60,
        is_persistence=True,
        objective="Obtain Global/Tenant admin over the cloud environment.",
        prerequisite_note="An abusable role assignment, app owner right, or consent.",
        steps=(
            _p("# add credentials to a privileged service principal, or self-assign a role", "Abuse the discovered path to elevate.", "Admin-level control of the tenant."),
        ),
        success_indicator="Tenant/Global admin access is confirmed.",
        fallback_technique_ids=("T1548",),
        detection="Role assignments; new SP credentials; privileged app changes.",
        attributed_actors=frozenset({"APT29"}),
        references=("https://attack.mitre.org/techniques/T1098/",),
    ),
    Play(
        technique_id="T1484.002",
        name="Hybrid trust abuse (on-prem DA → cloud)",
        tactic=Tactic.PRIVILEGE_ESCALATION,
        summary="Pivot Domain Admin into the cloud tenant via the identity sync trust.",
        requires=frozenset({CAP_DOMAIN_ADMIN}),
        provides=frozenset({CAP_CLOUD_ADMIN}),
        platforms=frozenset({AZ}),
        noise=3, difficulty=3, reliability=3, est_minutes=90,
        objective="Turn on-prem domain control into cloud tenant control.",
        prerequisite_note="Entra Connect / seamless SSO / federation reachable from on-prem.",
        steps=(
            _p("# abuse the sync account (AADInternals) or federation trust", "Leverage the hybrid identity trust.", "A cloud identity with admin rights."),
        ),
        success_indicator="Privileged cloud access is obtained from on-prem DA.",
        fallback_technique_ids=("T1098",),
        detection="Sync-account abuse; new federation trusts; token forgery.",
        attributed_actors=frozenset({"APT29"}),
        references=("https://attack.mitre.org/techniques/T1484/002/",),
    ),
    Play(
        technique_id="T1114.002",
        name="Remote Email Collection (M365 / Graph)",
        tactic=Tactic.COLLECTION,
        summary="Read target mailboxes in the cloud via API with a cloud identity.",
        requires=frozenset({CAP_CLOUD_ACCOUNT}),
        provides=frozenset({CAP_EMAIL_ACCESS, CAP_SENSITIVE_DATA_ACCESS}),
        platforms=frozenset({AZ, CLD}),
        noise=2, difficulty=2, reliability=4, est_minutes=45,
        objective="Access cloud mailboxes relevant to the objective.",
        prerequisite_note="A cloud identity (or app) with mail read scope.",
        steps=(
            _p("# use Graph API mail.read with the token to pull target mail", "Read/stage cloud mailbox content.", "Readable target mailbox content."),
        ),
        success_indicator="Target cloud mailbox content is accessible.",
        fallback_technique_ids=("T1114",),
        detection="Unusual Graph mail.read volume; risky app tokens.",
        references=("https://attack.mitre.org/techniques/T1114/002/",),
    ),
    Play(
        technique_id="T1530",
        name="Data from Cloud Storage",
        tactic=Tactic.COLLECTION,
        summary="Pull objective data from cloud buckets/blobs the identity can reach.",
        requires=frozenset({CAP_CLOUD_ACCOUNT}),
        provides=frozenset({CAP_SENSITIVE_DATA_ACCESS}),
        platforms=frozenset({CLD, AZ}),
        noise=2, difficulty=2, reliability=4, est_minutes=45,
        objective="Locate and stage in-scope data in cloud storage.",
        prerequisite_note="A cloud identity with storage read access.",
        steps=(
            _p("# enumerate and read reachable buckets/blobs/containers", "Find and stage sensitive cloud objects.", "Objective data staged from cloud storage."),
        ),
        success_indicator="Objective data is reachable in cloud storage.",
        fallback_technique_ids=("T1213",),
        detection="Bulk storage reads/downloads from one principal.",
        references=("https://attack.mitre.org/techniques/T1530/",),
    ),
]
